# Welcome to serverless. Read the docs
# https://serverless.com/framework/docs/
# Serverless.yml is the configuration the CLI
# uses to deploy your code to your provider of choice
# The `service` block is the name of the service
service: image-processor
# The `provider` block defines where your service will be deployed

plugins:
  - serverless-offline


custom:
  bucket: msc-group4-cloud-repo
 
# The `provider` block defines where your service will be deployed
provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-2
  stackName: image-processor
  apiGateway:
    binaryMediaTypes:
      - '*/*'
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
        - "s3:GetObject"
      Resource:
        - "arn:aws:s3:::${self:custom.bucket}/*"
# The `functions` block defines what code to deploy
functions:
  UploadFileHome:
    handler: fileUploaderHome.handler
    timeout: 120
    # The `events` block defines how to trigger the handler.helloWorld code
    events:
      - http:
          path: upload
          method: post
          cors:
              origin: '*'
              headers: # <-- Specify allowed headers
                - Content-Type
                - X-Amz-Date
                - Authorization
                - X-Api-Key
                - X-Amz-Security-Token
                - X-Amz-User-Agent
              allowCredentials: false
    environment:
      Bucket: ${self:custom.bucket}
  UserRegistration:
    handler: userRegistration.handler
    timeout: 120
    # The `events` block defines how to trigger the handler.helloWorld code
    events:
      - http:
          path: create-user
          method: post
          cors:
            origin: '*'
            headers: # <-- Specify allowed headers
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false